services:

  api:
    container_name: kanban-api
    build:
      context: .
    depends_on:
      - postgres
    environment:
      # note that "postgres" has to match the name of the postgres container
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/kanban"
      SPRING_DATASOURCE_USERNAME: kanban
      SPRING_DATASOURCE_PASSWORD: kanban
      SPRING_LOGGING_LEVEL_ROOT: INFO
      SPRING_SERVER_PORT: 8080
      NAVEN_OPTS: -Dmaven.repo.local=/root/.m2/repository
    networks:
      - kanban-network
    ports:
      - 8083:8080
    volumes:
      - "${HOME}/.m2:/root/.m2"

  postgres:
    container_name: kanban-postgres
    image: postgres:13-alpine
    restart: always
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    environment:
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
      POSTGRES_DB: kanban
    ports:
      - 5439:5432
    networks:
      kanban-network:
networks:
  kanban-network:
